#Neural Network
nn: LSTM

nnParams:
  # lstmFeatures: [6,9]

  lstmFeatures: [6,9,3] #[inputdim, hiddendim, layers]
  mlpFeatures: [9,16,3]

  mlpTemFeatures: [10,20,1]
  hasParams: false

#wrapper settings
wrapper: true
wrapperParams:
  evolveLen: 50
  inputMode: mvWin
  inputFnArgs:
    inputLen: 10
  hasAuxiliary: fal

testParams:
  evolveLen: 4990
  inputMode: mvWin
  inputFnArgs:
    inputLen: 10
  hasAuxiliary: fal

testLen: 5000

dataPath: /ehome/jiali/DeepModelZoo/lorenz_dataset3_1_full.npz
  
batchSize: 8192
epochs: 501

scheduler: ReduceLROnPlateau
schedulerParams:
  mode: min
  factor: 0.5
  patience: 20
  verbose: true
  threshold_mode: rel
  cooldown: 10
  min_lr: 1.e-6


optimizer: Adam
lr: 1.e-3


printInterval: 10
saveInterval: 50
savePath: /storage/jiali/